package minerful.gui.model;

@Deprecated
public enum TemplateEnum {
	/*
	PRECEDENCE,
	RESPONDEDEXISTENCE,
	COEXISTENCE,
	RESPONSE,
	ALTERNATERESPONSE,
	ALTERNATEPRECEDENCE,
	CHAINRESPONSE,
	CHAINPRECEDENCE,
	SUCCESSION,
	ALTERNATSUCCESION,
	CHAINSUCCESSION,
	NOTSUCCESSION,
	NOTCHAINSUCCESSION,
	NOTCOEXISTENCE;
	 */
}